require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'IntegrationProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for IntegrationProject
  config = use_native_modules!
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
    
  use_flipper!()
    
  pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
  end

  post_install do |installer|
    react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  target 'IntegrationProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntegrationProjectUITests' do
    # Pods for testing
  end

end
